### ISSUE TITLE
Crash caused by Miner's Luck modifier not checking whether other mod is installed

### ISSUE THREAD

**Issue by Travis9x** [ianm1647/bettercompat#2]
In short, Miner's Luck tried to add an additional drop from Ice & Fire, but I don't have Ice & Fire installed in my modpack.  There are other mods that can add sapphires to the game, so it should not assume that we must have Ice & Fire to make parts out of sapphires.

Full crash report is attached:
[crash-2022-03-26_17.24.01-server.txt](https://github.com/ianm1647/bettercompat/files/8356522/crash-2022-03-26_17.24.01-server.txt)
.

**Comment by ianm1647** [comment]
i know this is old but i will have that fixed in a new update
