### ISSUE TITLE
Materials for Ice and Fire not showing

### ISSUE THREAD

**Issue by Ace1362** [ianm1647/bettercompat#3]
Currently not seeing the materials for ice and fire loading 
- Sapphire
- Dragonbone
- Amethyst
- Witherbone (there is a necrotic bone one though it looks like from tinkers)

using Tinkers **TConstruct-1.16.5-3.1.3.271.jar**
Compact **bettercompat-0.3.3-1.16.5-36.2.8.jar**

**Comment by ianm1647** [comment]
update your mod to the current version

**Comment by Ace1362** [comment]
weird I guess I was behind a bit, I "updated" when an update button showed up but it put me behind like 5 versions
